### PR TITLE
Add a strided batched method for getrf

### PR DESCRIPTION
**Pull request by maleadt**
Creating a bunch of views is expensive when dealing with a large batchsize.
cc @YingboMa, ref https://github.com/JuliaDiffEq/DiffEqGPU.jl/issues/25

### CODE REVIEW

**Comment by kshyatt** [comment]
lgtm, let's see what bors says :)

**Comment by maleadt** [comment]
Huh, bors failure but gitlab is green? Let's try that again.
bors r+

**Comment by maleadt** [comment]
Now bors crashed. This PR seems cursed.

**Pull request merged**
