### PR TITLE
Let cublasXT use host memory

### PR DESCRIPTION
**Pull request by kshyatt**
the whole point of cublasXT is to allocate host arrays that are too big for one GPU, and then it farms out the chunks for you. not sure I did the wrapper updates right. seeing a lot of ugly test failures if anyone else wants to take a run at this.

### CODE REVIEW

**Comment by maleadt** [comment]
Only issue was an OOM, so that actually looks rather good? Or don't we have good test coverage for cublasXt?

**Comment by kshyatt** [comment]
The difference is that our previous coverage was with GPU pointers only. I
had to modify the wrappers to accept CPU pointers too (that's actually the
normal operation mode of cublasXt) and then add tests for it.

**Comment by kshyatt** [comment]
Tests passed for the `pool` tests, there was just a job timeout. Good to merge?

**Comment by maleadt** [comment]
I restarted the rests.
bors r+

**Pull request merged**
