### PR TITLE
adds wrappers for syevjBatched/heevjBatched family of CUSOLVER functions

### PR DESCRIPTION
**Pull request by electronsandstuff**
Implemented batch hermitian/symmetric eigensolving from cuSolver.  Used same solver default parameters as sygvj which converges to machine precision for the 15x15 test matrices in the unit tests.

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! Could you add some tests?

**Comment by maleadt** [comment]
Thanks!
bors try

**Comment by maleadt** [comment]
bors try

**Comment by electronsandstuff** [comment]
It looks like it got stuck on a different test than last time.  It was Julia:1.4 now it's Arm64.

**Comment by maleadt** [comment]
The ARM can happen, it shouldn't cause bors to timeout. I wonder if our CI times have increased lately, it sure feels like it. Let's check another time to be sure:
bors r+

**Comment by maleadt** [comment]
Not sure what's up with CI. I rebooted the servers.
bors try

**Comment by maleadt** [comment]
CI is flaky, but that doesn't look to be related to this PR. Let's merge this.

**Pull request merged**
