### PR TITLE
Implement a few sparse array basics

### PR DESCRIPTION
**Pull request by janEbert**
Namely `getindex`, `nnz`, `nonzeros` and `nonzeroinds`. These also fix the `show` methods for `SparseCuVector` and `SparseCuMatrixCS{C,R}` (albeit using scalar indexing). 

#451

### CODE REVIEW

**Comment by maleadt** [comment]
You need to wrap in calls to `Array` yourself to download the values before comparison, and avoid scalar iteration.

**Comment by janEbert** [comment]
So for the tests I should write, for example,
`@test Array(nonzeros(d_x)) == nonzeros(x)`?
Or do you mean I should re-implement `show` to wrap the returned values in `Array`?
Or something else entirely?

**Comment by maleadt** [comment]
No `@test Array(nonzeros(d_x)) == nonzeros(x)` is fine. There's were some other CI failures too, though.

**Comment by amontoison** [comment]
@janEbert bump
Very useful pull request! `show` doesn't work for an `CuSparseMatrixCSC` otherwise.

**Comment by janEbert** [comment]
Hey! Thanks for the interest and reminder, I kind of forgot about this.
I'll try to fix everything today. :)

**Comment by janEbert** [comment]
Hey, this is fixed (fingers crossed ;) ) and can be retried.
Showing `CuSparseMatrixCS{C,R}` still won't work though as I need to either implement `getindex` or write a GPU-compliant `show` for `CuSparseMatrixCS{C,R}`.

I had already started work on implementing `getindex` and will commit it to this PR when done (unless the PR has already been merged then).

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
> I had already started work on implementing `getindex` and will commit it to this PR when done (unless the PR has already been merged then).

Great! Let's keep this PR open then.

**Comment by janEbert** [comment]
It's really weird; going to the commits of [my PR branch](https://github.com/janEbert/CuArrays.jl/commits/sparse) I see the commits were uploaded correctly but they still aren't listed here; what should I do?

**Comment by janEbert** [comment]
We can close this so I can open a new PR with the same branch that (hopefully) does not have the issue. Or this is merged and I open a new PR for `getindex`. Or we try and fix it another way. Whatever you want. :)

**Comment by janEbert** [comment]
Sorry for the triple post; changing base branches did the trick.

**Comment by amontoison** [comment]
@janEbert, Is it ready to be merged?

**Comment by janEbert** [comment]
Absolutely!

**Comment by maleadt** [comment]
Oh, I thought you wanted to push additional changes to chis branch. Let's merge it then:
bors r+

**Comment by janEbert** [comment]
> Oh, I thought you wanted to push additional changes to chis branch.

Absolutely, though I was quickly done with those. Afterwards, there was a Github bug preventing the changes from showing up.

The errors were due to me using Julia 1.4 `begin` indexing. I de-sugared those operations to use `firstindex` now so please try again.

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
CI failure unrelated.

**Pull request merged**
