### PR TITLE
Continue working on 0.7 support

### PR DESCRIPTION
**Pull request by vchuravy**
There is still work needed in JuliaGPu/GPUArrays.jl#127

- [x] mapreduce
- [x] indexing 
- [x] some broadcasts don't compile

### CODE REVIEW

**Comment by vchuravy** [comment]
So the major blocker is that GPUArrays likes UInt32 and CUDAnative prefers Int

**Comment by maleadt** [comment]
One disadvantage of this approach is that we need an truncation when using intrinsics/device functions that only accept (unsigned) 32-bits integers:
https://github.com/JuliaGPU/CUDAnative.jl/blob/8db06cee0ed6ec217a9b2c363d11fb4069f1a1d1/src/device/intrinsics/warp_shuffle.jl#L39-L43
but at least we fully control that invocation of `unsafe_trunc`

**Comment by vchuravy** [comment]
Current roadblock:

```
julia> rand(CuArray{T}, 5, 5, 10, 10)
ERROR: CUDA error: invalid argument (code #1, ERROR_INVALID_VALUE)
Stacktrace:
 [1] #upload!#10(::Bool, ::Function, ::CUDAdrv.Mem.Buffer, ::Base.RefArray{NTuple{4,UInt32},Array{NTuple{4,UInt32},1},Nothing}, ::Int64, ::CUDAdrv.CuStream) at C:\Users\t-vachur\.julia\dev\CUDAdrv\src\memory.jl:235
 [2] upload! at C:\Users\t-vachur\.julia\dev\CUDAdrv\src\memory.jl:229 [inlined] (repeats 2 times)
 [3] copyto! at C:\Users\t-vachur\.julia\dev\CuArrays\src\gpuarray_interface.jl:94 [inlined]
 [4] copyto! at C:\Users\t-vachur\.julia\dev\GPUArrays\src\abstractarray.jl:111 [inlined]
 [5] (::getfield(GPUArrays, Symbol("##75#78")){CuArray{Float32,4},CUDAdrv.CuDevice})() at C:\Users\t-vachur\.julia\dev\GPUArrays\src\random.jl:52
 [6] get!(::getfield(GPUArrays, Symbol("##75#78")){CuArray{Float32,4},CUDAdrv.CuDevice}, ::Dict{Any,Any}, ::CUDAdrv.CuDevice) at .\dict.jl:453
 [7] cached_state at C:\Users\t-vachur\.julia\dev\GPUArrays\src\random.jl:49 [inlined]
 [8] rand!(::CuArray{Float32,4}) at C:\Users\t-vachur\.julia\dev\GPUArrays\src\random.jl:58
 [9] rand(::Type{CuArray{Float32,N} where N}, ::Type{Float32}, ::Int64, ::Int64, ::Vararg{Int64,N} where N) at C:\Users\t-vachur\.julia\dev\GPUArrays\src\random.jl:77
 [10] rand(::Type{CuArray{Float32,N} where N}, ::Int64, ::Int64, ::Int64, ::Vararg{Int64,N} where N) at C:\Users\t-vachur\.julia\dev\GPUArrays\src\random.jl:70
 [11] top-level scope at none:0
```

**Comment by vchuravy** [comment]
@MikeInnes & @SimonDanisch  it would be great to get your help on pushing this to completion.
Current status with https://github.com/JuliaGPU/GPUArrays.jl/pull/130,

```
Test Summary:                    | Pass  Error  Total
CuArrays                         | 1823     81   1904
  GPUArray Testsuite             |  633      4    637
    parallel execution interface |    7             7
    base functionality           |   20            20
    BLAS                         |   11            11
    FFT with ND = 1              |    4             4
    FFT with ND = 2              |    4             4
    FFT with ND = 3              |    4             4
    Construction                 |  312           312
    Linalg                       |           2      2
      transpose                  |           1      1
      PermuteDims                |           1      1
    mapreduce                    |  188           188
    indexing                     |   83      2     85
      Indexing with Float32      |   34            34
      multi dim, sliced setindex |              No tests
      Indexing with Int32        |   34            34
      multi dim, sliced setindex |           1      1
      Indexing with Float32      |    3             3
      Indexing with Int32        |    2      1      3
      issue #42 with Float32     |    3             3
      issue #42 with Int32       |    3             3
      Colon() Float32            |    2             2
      Colon() Int32              |    2             2
  Array                          |    6             6
  Indexing                       |    2             2
  PermuteDims                    |           3      3
  Concat                         |    5             5
  Broadcast                      |    5      1      6
  Broadcast Fix                  |           4      4
  Reduce                         |    6             6
  0D                             |           1      1
  Slices                         |    5             5
  BLAS                           |  953     35    988
    Level 1                      |   12     24     36
      T = Float32                |    3      7     10
      T = Float64                |    3      7     10
      T = Complex{Float32}       |    3      5      8
      T = Complex{Float64}       |    3      5      8
    Level 2                      |  941     11    952
      T = Float32                |    3             3
      T = Float64                |    3             3
      T = Complex{Float32}       |    3             3
      T = Complex{Float64}       |    3             3
      gbmv!                      |   12            12
      gbmv                       |    4             4
      symv!                      |    4             4
      symv                       |    4             4
      hemv!                      |    2             2
      hemv                       |    2             2
      sbmv!                      |    4             4
      sbmv                       |    4             4
      hbmv!                      |    4             4
      hbmv                       |    4             4
      tbmv!                      |    8             8
      tbmv                       |    8             8
      tbsv!                      |    8             8
      tbsv                       |    8             8
      trmv!                      |    4             4
      trmv                       |    4             4
      trsv!                      |    1      3      4
        elty = Float32           |    1             1
        elty = Float64           |           1      1
        elty = Complex{Float32}  |           1      1
        elty = Complex{Float64}  |           1      1
      trsv                       |           4      4
        elty = Float32           |           1      1
        elty = Float64           |           1      1
        elty = Complex{Float32}  |           1      1
        elty = Complex{Float64}  |           1      1
      ger!                       |    4             4
      syr!                       |    4             4
      her!                       |    2             2
      her2!                      |    2             2
      gemm!                      |           4      4
        elty = Float32           |           1      1
        elty = Float64           |           1      1
        elty = Complex{Float32}  |           1      1
        elty = Complex{Float64}  |           1      1
      gemm                       |    8             8
      gemm_batched!              |   40            40
      gemm_batched               |   40            40
      symm!                      |    4             4
      symm                       |    4             4
      syrk!                      |    4             4
      syrk                       |    4             4
      herk!                      |    2             2
      herk                       |    2             2
      syr2k!                     |    4             4
      syr2k                      |    4             4
      her2k!                     |    2             2
      her2k                      |    2             2
      trmm!                      |    4             4
      trmm                       |    4             4
      trsm!                      |    4             4
      trsm                       |    4             4
      trsm_batched!              |   40            40
      trsm_batched               |   40            40
      hemm!                      |    4             4
      hemm                       |    4             4
      geam!                      |   28            28
      geam                       |    4             4
      getrf_batched!             |  160           160
      getrf_batched              |   80            80
      getri_batched              |  120           120
      matinv_batched             |   40            40
      geqrf_batched!             |   40            40
      geqrf_batched              |   40            40
      gels_batched!              |   40            40
      gels_batched               |   40            40
      dgmm!                      |   12            12
      dgmm                       |    4             4
  cuSolver                       |   58     33     91
    elty = Float32               |   19      6     25
      potrf!                     |           1      1
      potrs!                     |    2      1      3
      getrf!                     |    2             2
      getrs!                     |    3             3
      geqrf!                     |    1             1
      ormqr!                     |    4             4
      orgqr!                     |    2             2
      sytrf!                     |           1      1
      gebrd!                     |           1      1
      gesvd!                     |           1      1
      qr                         |    5      1      6
    elty = Float64               |   13      9     22
      potrf!                     |           1      1
      potrs!                     |    2      1      3
      getrf!                     |           1      1
      getrs!                     |           1      1
      geqrf!                     |           1      1
      ormqr!                     |    4             4
      orgqr!                     |    2             2
      sytrf!                     |           1      1
      gebrd!                     |           1      1
      gesvd!                     |           1      1
      qr                         |    5      1      6
    elty = Complex{Float32}      |   13      9     22
      potrf!                     |           1      1
      potrs!                     |    2      1      3
      getrf!                     |           1      1
      getrs!                     |           1      1
      geqrf!                     |           1      1
      ormqr!                     |    4             4
      orgqr!                     |    2             2
      sytrf!                     |           1      1
      gebrd!                     |           1      1
      gesvd!                     |           1      1
      qr                         |    5      1      6
    elty = Complex{Float64}      |   13      9     22
      potrf!                     |           1      1
      potrs!                     |    2      1      3
      getrf!                     |           1      1
      getrs!                     |           1      1
      geqrf!                     |           1      1
      ormqr!                     |    4             4
      orgqr!                     |    2             2
      sytrf!                     |           1      1
      gebrd!                     |           1      1
      gesvd!                     |           1      1
      qr                         |    5      1      6
  FFT                            |   71            71
  FFT                            |   71            71
  Int FFT                        |    4             4
  Int FFT                        |    4             4
ERROR: LoadError: Some tests did not pass: 1823 passed, 0 failed, 81 errored, 0 broken.
```

**Comment by jekbradbury** [comment]
I'm getting a fatal error during tests:
```
(v0.7) pkg> test CuArrays
   Testing CuArrays
 Resolving package versions...
    Status `/tmp/tmpsdeSQs/Manifest.toml`                                                                                                                                                                                            [59/1836]
  [621f4979] AbstractFFTs v0.3.2
  [79e6a3ab] Adapt v0.2.0
  [9e28174c] BinDeps v0.8.9
  [b99e7846] BinaryProvider v0.4.0
  [3895d2a7] CUDAapi v0.4.3
  [c5f51814] CUDAdrv v0.8.4
  [be33ccc6] CUDAnative v0.8.5+ #master (https://github.com/JuliaGPU/CUDAnative.jl.git)
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v1.0.1
  [8f4d0f93] Conda v1.0.0
  [3a865a2d] CuArrays v0.6.2+ #vc/0.7 (https://github.com/JuliaGPU/CuArrays.jl.git)
  [163ba53b] DiffResults v0.0.3
  [b552c78f] DiffRules v0.0.7
  [7a1cc6ca] FFTW v0.2.3
  [9aa1b823] FastClosures v0.2.0
  [f6369f11] ForwardDiff v0.8.1
  [0c68f7d7] GPUArrays v0.2.4+ #master (https://github.com/JuliaGPU/GPUArrays.jl.git)
  [682c06a0] JSON v0.19.0
  [929cbde3] LLVM v0.9.13
  [1914dd2f] MacroTools v0.4.3
  [cecf6091] MicroLogging v0.2.0
  [872c559c] NNlib v0.4.0+ #master (https://github.com/FluxML/NNlib.jl.git)
  [77ba4419] NaNMath v0.3.2
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [276daf66] SpecialFunctions v0.6.0
  [90137ffa] StaticArrays v0.8.2
  [30578b45] URIParser v0.4.0
  [81def892] VersionParsing v1.1.1
  [2a0f44e3] Base64  [`/usr/bin/../share/julia/stdlib/v0.7/Base64`]
  [ade2ca70] Dates  [`/usr/bin/../share/julia/stdlib/v0.7/Dates`]
  [8bb1440f] DelimitedFiles  [`/usr/bin/../share/julia/stdlib/v0.7/DelimitedFiles`]
  [8ba89e20] Distributed  [`/usr/bin/../share/julia/stdlib/v0.7/Distributed`]
  [b77e0a4c] InteractiveUtils  [`/usr/bin/../share/julia/stdlib/v0.7/InteractiveUtils`]
  [76f85450] LibGit2  [`/usr/bin/../share/julia/stdlib/v0.7/LibGit2`]
  [8f399da3] Libdl  [`/usr/bin/../share/julia/stdlib/v0.7/Libdl`]
  [37e2e46d] LinearAlgebra  [`/usr/bin/../share/julia/stdlib/v0.7/LinearAlgebra`]
  [56ddb016] Logging  [`/usr/bin/../share/julia/stdlib/v0.7/Logging`]
  [d6f4376e] Markdown  [`/usr/bin/../share/julia/stdlib/v0.7/Markdown`]
  [a63ad114] Mmap  [`/usr/bin/../share/julia/stdlib/v0.7/Mmap`]
  [44cfe95a] Pkg  [`/usr/bin/../share/julia/stdlib/v0.7/Pkg`]
  [de0858da] Printf  [`/usr/bin/../share/julia/stdlib/v0.7/Printf`]
  [3fa0cd96] REPL  [`/usr/bin/../share/julia/stdlib/v0.7/REPL`]
  [9a3f8284] Random  [`/usr/bin/../share/julia/stdlib/v0.7/Random`]
  [ea8e919c] SHA  [`/usr/bin/../share/julia/stdlib/v0.7/SHA`]
  [9e88b42a] Serialization  [`/usr/bin/../share/julia/stdlib/v0.7/Serialization`]
  [1a1011a3] SharedArrays  [`/usr/bin/../share/julia/stdlib/v0.7/SharedArrays`]
  [6462fe0b] Sockets  [`/usr/bin/../share/julia/stdlib/v0.7/Sockets`]
  [2f01184e] SparseArrays  [`/usr/bin/../share/julia/stdlib/v0.7/SparseArrays`]
  [10745b16] Statistics  [`/usr/bin/../share/julia/stdlib/v0.7/Statistics`]
  [8dfed614] Test  [`/usr/bin/../share/julia/stdlib/v0.7/Test`]
  [cf7118a7] UUIDs  [`/usr/bin/../share/julia/stdlib/v0.7/UUIDs`]
  [4ec0a83e] Unicode  [`/usr/bin/../share/julia/stdlib/v0.7/Unicode`]
...[lots of depwarns + test failures]...
Illegal inttoptr
          %ptrint.i = ptrtoint %jl_value_t addrspace(10)* %13 to i64, !dbg !84

signal (6): Aborted
in expression starting at /root/.julia/packages/CuArrays/EsAwz/test/runtests.jl:40
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
runOnFunction at /buildworker/worker/package_linux64/build/src/llvm-gc-invariant-verifier.cpp:178
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/julia/libLLVM-6.0.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /usr/bin/../lib/julia/libLLVM-6.0.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /usr/bin/../lib/julia/libLLVM-6.0.so (unknown line)
LLVMRunPassManager at /usr/bin/../lib/julia/libLLVM-6.0.so (unknown line)
macro expansion at /root/.julia/packages/LLVM/kNtFa/src/base.jl:18 [inlined]
LLVMRunPassManager at /root/.julia/packages/LLVM/kNtFa/lib/6.0/libLLVM_h.jl:2689 [inlined]
run! at /root/.julia/packages/LLVM/kNtFa/src/passmanager.jl:34 [inlined]
optimize! at /root/.julia/packages/CUDAnative/A1gzs/src/compiler.jl:606
#compile_function#66 at ./logging.jl:320
compile_function at /root/.julia/packages/CUDAnative/A1gzs/src/compiler.jl:625 [inlined]
#cufunction#67 at /root/.julia/packages/CUDAnative/A1gzs/src/compiler.jl:702
unknown function (ip: 0x7fe280ec0346)
#cufunction at ./none:0
unknown function (ip: 0x7fe280ebf27d)
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
macro expansion at /root/.julia/packages/CUDAnative/A1gzs/src/execution.jl:222 [inlined]
_cuda at /root/.julia/packages/CUDAnative/A1gzs/src/execution.jl:180
unknown function (ip: 0x7fe1bf9eaf82)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
macro expansion at ./gcutils.jl:87 [inlined]
_gpu_call at /root/.julia/packages/CuArrays/EsAwz/src/gpuarray_interface.jl:64
gpu_call at /root/.julia/packages/GPUArrays/QYnXv/src/abstract_gpu_interface.jl:151
unknown function (ip: 0x7fe1bf9ea223)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
gpu_call at /root/.julia/packages/GPUArrays/QYnXv/src/abstract_gpu_interface.jl:128 [inlined]
copyto! at /root/.julia/packages/GPUArrays/QYnXv/src/broadcast.jl:13 [inlined]
copyto! at ./broadcast.jl:768 [inlined]
copy at ./broadcast.jl:744 [inlined]
materialize at ./broadcast.jl:724 [inlined]
#14 at ./none:0
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
testf at /root/.julia/packages/CuArrays/EsAwz/test/runtests.jl:35
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1089 [inlined]
macro expansion at /root/.julia/packages/CuArrays/EsAwz/test/runtests.jl:42 [inlined]
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 [inlined]
top-level scope at /root/.julia/packages/CuArrays/EsAwz/test/runtests.jl:41
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:841
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:865
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1040
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
exec_options at ./client.jl:239
_start at ./client.jl:432
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1538 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:112
main at /buildworker/worker/package_linux64/build/ui/repl.c:233
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /usr/bin/julia (unknown line)
Allocations: 170211491 (Pool: 170184333; Big: 27158); GC: 407
ERROR: LoadError: failed process: Process(`/usr/bin/julia -Cnative -J/usr/lib/julia/sys.so --compile=yes --depwarn=yes --color=yes --compiled-modules=yes --startup-file=no --code-coverage=none /root/.julia/packages/CuArrays/EsAwz/test/run
tests.jl`, ProcessSignaled(6)) [0]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:712 [inlined]
 [3] #run#509(::Bool, ::Function, ::Cmd) at ./process.jl:670
 [4] run(::Cmd) at ./process.jl:668
 [5] top-level scope at /root/.julia/packages/CuArrays/EsAwz/test/runtests.jl:5
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1040
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] include(::String) at ./client.jl:398
 [10] top-level scope at none:0
in expression starting at /root/.julia/packages/CuArrays/EsAwz/test/runtests.jl:3
ERROR: Package CuArrays errored during testing
```

**Comment by jekbradbury** [comment]
It seems like @vchuravy's test results are with yet a different GPUArrays branch? I'm getting
```
Test Summary:                           | Pass  Error  Total
CuArrays                                | 1485    267   1752
  GPUArray Testsuite                    |  353    146    499
...
```
with `CuArrays#vc/0.7`, `GPUArrays#sd/07`, and `CUDAnative#master`.

**Comment by SimonDanisch** [comment]
I'm getting this nice [segfault](https://gist.github.com/SimonDanisch/0ad61e3e30a8529e73b681ed0f36df37#file-segfault)...
Pretty sure  it has been working on GPUArrays#master + CuArrays#vc/0.7 before..
This is rc3 now, with `]up CUDAnative`.
@maleadt any idea what could have changed so dramatically?

**Comment by maleadt** [comment]
`Exception: UNKNOWN`, never seen that before. Try building with `LLVM_ASSERTIONS=1` and `FORCE_ASSERTIONS=1` to see if we hit something earlier on.

**Comment by SimonDanisch** [comment]
Running the tests also crash my whole pc/gpu driver ... 

@jekbradbury the main difference between master and sd/07 are the changes to Int64 - which have been tested and we didn't find any regressions. So I guess they just make things worse right now!
@maleadt sorry, I'm not on a windows that can build from source right now...

**Comment by maleadt** [comment]
Contained in https://github.com/JuliaGPU/CuArrays.jl/pull/105

**Pull request closed without merging**
