### PR TITLE
Adjust NNlib API for recent NNlib overhaul

### PR DESCRIPTION
**Pull request by staticfloat**
Also implement some compatibility shims so that client code may not have to adjust just yet.

Note that I am unable to test this locally as cyclops is having a bad day, but hopefully the changes are simple enough that remote CI will be good enough. :)

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks!
bors try

**Comment by staticfloat** [comment]
Also note that I didn't change any of the test stuff, so those tests will still be using the compatibility shims that I added.  For GPU code, I don't think we will get that much performance benefit from having convolution parameters embedded in the type domain, so using the compatibility shims probably won't hurt anything.  (In CPU land, I'm hoping that having statically-known parameters for things like stride, padding, etc... will eventually lead us to being able to create very efficient, highly fused kernels)

**Comment by staticfloat** [comment]
bors try

**Comment by maleadt** [comment]
Hmm, looks like we haven't configured any permissions on the bots yet.
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
Okay, I didn't realize that the tests were comparing against the NNlib versions.  So we do need to upgrade the tests.

bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
ONE.  MORE.  TIME.

bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
bors try

**Comment by maleadt** [comment]
Would it be useful to migrate these wrappers to NNlib.jl and have them tested there (behind a Requires check)?

**Comment by staticfloat** [comment]
I... don't think so?  It's fine to have these here, IMO.  The reason I'm fighting `bors` so much here is just that I don't have access to a CUDA machine at the moment.  :P

**Comment by staticfloat** [comment]
bors try

**Comment by staticfloat** [comment]
Alright, I think this is where I'm gonna have to leave it for tonight; with a `CUDNNError(code 9, CUDNN_STATUS_NOT_SUPPORTED)`.  Not entirely sure why I'm getting that, but I probably have some bad value for some parameter I suppose?

**Comment by vchuravy** [comment]
The argument for not having them in here is that the dependency arrow goes the wrong way. CuArray is a dependency of NNLib for GPU support

**Comment by kshyatt** [comment]
I can reproduce this really weird error about `DenseConvDims not defined`

**Comment by staticfloat** [comment]
> I can reproduce this really weird error about DenseConvDims not defined

Do you have `NNlib#master` installed?

**Comment by kshyatt** [comment]
OK I'm caught up to where this PR is! So the error is from:

```julia
      @test_nowarn NNlib.conv!(cu(y), cu(x), cu(w), cdims; algo=1)                                                   
      @test_nowarn NNlib.∇conv_data!(cu(x), cu(y), cu(w), cdims; algo=1)                                             
      @test_nowarn NNlib.∇conv_filter!(cu(w), cu(x), cu(y), cdims; algo=1)                                           
      @test_nowarn NNlib.conv!(cu(y), cu(x), cu(w), cdims; algo=0)                                                    
      @test_nowarn NNlib.∇conv_data!(cu(x), cu(y), cu(w), cdims; algo=0)                                              
      @test_nowarn NNlib.∇conv_filter!(cu(w), cu(x), cu(y), cdims; algo=0)                                            
      @test_nowarn NNlib.conv!(cu(y), cu(x), cu(w), cdims; algo=2)                                                    
      @test_nowarn NNlib.∇conv_data!(cu(x), cu(y), cu(w), cdims; algo=2)                                              
      @test_nowarn NNlib.∇conv_filter!(cu(w), cu(x), cu(y), cdims; algo=2)
```
`algo=0` works, the other two do not. This might be a `CUDNN` issue, not ours. The specific problematic function is:
`cudnnGetConvolutionForwardWorkspaceSize(::CuArrays.CUDNN.TensorDesc, ::CuArrays.CUDNN.FilterDesc, ::CuArrays.CUDNN.ConvDesc, ::CuArrays.CUDNN.TensorDesc, ::Int64, ::Base.RefValue{Int32}) at .../.julia/dev/CuArrays/src/dnn/libcudnn.jl:276`

**Comment by kshyatt** [comment]
There's some dimensional broadcasting issue here but the other tests are working. I think some algorithms don't work with dilation/stride.

**Comment by kshyatt** [comment]
bors try

**Pull request closed without merging**
