### PR TITLE
Changes in Conv API

### PR DESCRIPTION
**Pull request by tejank10**
The changes to the `conv` API of NNlib have been proposed in [#54](https://github.com/FluxML/NNlib.jl/pull/54). This PR makes the corresponding changes in order to make it compatible with CuArrays.

### CODE REVIEW

**Comment by vchuravy** [comment]
In #222 I also had a compatibility layer to current NNLib. Not sure if that is really needed but it would allow us to merge this before the NNLib changes land.

**Comment by vchuravy** [comment]
bors try

**Comment by MikeInnes** [comment]
bors try

**Comment by MikeInnes** [comment]
Note that this is an API change; I'll change the current version number so it's clear we need a new minor.

**Comment by maleadt** [comment]
Doesn't this need a REQUIRE update?

**Comment by MikeInnes** [comment]
As in, bumping the NNlib version? We do need to but NNlib isn't tagged yet. Don't know if there's any downside to just putting a future version in though, given that we do CI with master anyway.

**Comment by maleadt** [comment]
> Don't know if there's any downside to just putting a future version in though, given that we do CI with master anyway.

Yeah, I typically do it early not to forget it when we end up tagging. But it's the same to me, I'm on `master` anyway.

**Pull request merged**
