### PR TITLE
Dup of nnlib_overhaul [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by kshyatt**
opened a new PR to test the rebased on top of master version without corrupting Elliot's PR.

### CODE REVIEW

**Comment by kshyatt** [comment]
bors try

**Comment by maleadt** [comment]
Sorry, I broke CI trying to update some scripts for the upcoming JuliaRegistrator...

**Comment by kshyatt** [comment]
Never apologize, never surrender

**Comment by maleadt** [comment]
CI should be fixed, if you rebase again it should work.

**Comment by kshyatt** [comment]
bors try

**Comment by maleadt** [comment]
> DO NOT MERGE

> Build succeeded

So tempting...

**Comment by maleadt** [comment]
If https://github.com/FluxML/NNlib.jl/pull/94 lands, be sure to add NNlib 0.6 compatibility to Project.toml before merging this.

**Comment by kshyatt** [comment]
It's landed.

**Comment by staticfloat** [comment]
Thanks so much @kshyatt!  I'm going to close mine in favor of this.  I don't really know how to add compatibility bounds either.

**Pull request merged**
