### PR TITLE
Fix adapt to Array for Flux.jl

### PR DESCRIPTION
**Pull request by Roger-luo**
the `cpu` conversion doesn't work in Flux:

https://github.com/FluxML/Flux.jl/issues/508

This should fix it.

### CODE REVIEW

**Comment by Roger-luo** [comment]
Don't how to test this tho, didn't find any existing tests for `adapt`

**Comment by maleadt** [comment]
Put my comment on the wrong issue, https://github.com/FluxML/Flux.jl/issues/508#issuecomment-444478355, but care to add a test?

**Comment by Roger-luo** [comment]
@maleadt could you run the tests again?

**Comment by Roger-luo** [comment]
bors r+


(can I enable the test as well? XD)

**Comment by Roger-luo** [comment]
Okay... I use `\approx` instead, guess this is why the test failed, could run pls run it again? this passed locally...

**Comment by maleadt** [comment]
Oh, I needed a different command to give you permission to `r+`:
bors delegate+
bors r+

**Pull request merged**
