### PR TITLE
Allow CuArrays to initialise if there is no CUDA/GPU on the system

### PR DESCRIPTION
**Pull request by tanhevg**
#371 
Wrap initialisation of active context in a try/catch

### CODE REVIEW

**Comment by maleadt** [comment]
`configured` should be false if CUDA is not working, how come that isn't the case on your system?

**Comment by tanhevg** [comment]
> `configured` should be false if CUDA is not working, how come that isn't the case on your system?

I guess this is because I based my PR on `v1.0.2`. With the latest changes on `master` the PR might be obsolete

**Comment by tanhevg** [comment]
> `configured` should be false if CUDA is not working, how come that isn't the case on your system?

Yeah, I guess I have based the PR on the `v1.0.2` code. There were lots of changes in `master` that made it obsolete. Although now attempt to use `CuArrays#master` blows up if there is no CUDA/GPU, which brings us back to the "two sets of tomls" problem.

**Comment by tanhevg** [comment]
Reverted the previous change, and made another one such that version checking does not blow up if there is no CUDA; please re-review.

**Comment by maleadt** [comment]
Thanks. I'm currently restructuring how CUDA packages are loaded, so I'll be sure to incorporate these changes over there.

I'm wondering though, why do you want CuArrays to be loadable without CUDA/GPU? Would it be equivalent if only one of those packages, say CUDAapi, would be loadable without CUDA/GPU, providing functions like `has_cuda` and `has_gpu`? It would greatly simplify the package loading code. So concretely:

```julia
using CUDAapi # never fails
if has_cuda() && has_gpu()
  using CuArrays
end
```

cc @MikeInnes @ChrisRackauckas who have similar conditional module loading paths
(I'm trying to get rid of `Pkg.build` so that should further improve the conditional loading use case)

**Comment by ChrisRackauckas** [comment]
CUDAapi really should have those functions. That as a standard setup would be really nice to have.

**Comment by MikeInnes** [comment]
That seems like a good setup. If errors are only thrown when you try to use CuArrays, rather than at build time, that enables us to do things like using the CUDA automatically in Flux, which would be a big boon. I'm also not sure why you'd want to load CuArrays itself without the GPU though (and we have to at some point warn users that it isn't working, if they are expecting it to).

**Comment by tanhevg** [comment]
> Would it be equivalent if only one of those packages, say CUDAapi, would be loadable without CUDA/GPU, providing functions like `has_cuda` and `has_gpu`? It would greatly simplify the package loading code.

Not sure I agree. All modules that use `CuArrays` would have to wrap all structures that reference `CuArray` (or any other type from `CuArrays` for that matter) in this `if has_cuda() && has_gpu()` clause. Otherwise, the module will not precompile. So with this approach we'll end up with anyone using `CuArrays` having to pepper their code with the if statements, which is not nice.

I think it is better for the module to be self-contained and loadable under a few well defined configurations, e.g. CUDA not installed, and CUDA installed properly. Especially, given that this is really not that hard to achieve.

**Comment by MikeInnes** [comment]
Flux must be one of the more complex users of CuArrays, and even there it's pretty simple. Just wrap one `if` around an `include` statement that has the compat code (the same thing we do with Requires now). Even if it weren't simple, *someone* has to write that if statement, and I'm strongly in favour of doing that once in packages rather than making users do it.

Technical ease is not really the issue here; the harder design problem is how we avoid CUDA silently failing when a user was expecting it to work, and needs to be aware of an issue on their system. The later we push this, the more potential frustration for that group, which means we have ourselves a tradeoff.

**Comment by ChrisRackauckas** [comment]
>Technical ease is not really the issue here; the harder design problem is how we avoid CUDA silently failing when a user was expecting it to work, and needs to be aware of an issue on their system. The later we push this, the more potential frustration for that group, which means we have ourselves a tradeoff.

Even when it doesn't fail, people are still getting warnings. CUDAnative really shouldn't be throwing a warning if there's no cudnn since only a small group actually cares about that, so the warning should be in a more targeted place. I think with the right if statements and if packages want to do fancy things, throw the right errors/warnings, everything will be clean. And so add `has_cudnn()` to the list and I think we have the right tools for packages to make it clean.

**Comment by tanhevg** [comment]
>  I'm also not sure why you'd want to load CuArrays itself without the GPU though (and we have to at some point warn users that it isn't working, if they are expecting it to).

I just to write as little CUDA-specifict code as possible; prefer the modules that I use to do stuff for me.  Ditto if I am writing a module myself - prefer the `if` statement to be written once in `CuArrays`, than having to write it myself.

Currently, with this PR merged in, an attempt to `using CuArrays` on a machine without CUDA/GPU will produce a warning, and a call to the actual CUDA code will error. So I think we are fine on warnings/errors side.

**Comment by maleadt** [comment]
> prefer the `if` statement to be written once in `CuArrays`, than having to write it myself

Except that you still need to add an `if` statement to your code, namely to check whether the now successfully-loaded `CuArrays` module is actually functional. It's also not a single check in CuArrays, since the package needs to check whether _its_ dependencies (CUDAdrv and CuArrays) are actually functional.

**Comment by maleadt** [comment]
Superseded by https://github.com/JuliaGPU/CuArrays.jl/pull/375 and https://github.com/JuliaGPU/CUDAapi.jl/pull/84

**Pull request closed without merging**
