### PR TITLE
flipkernel support and tests

### PR DESCRIPTION
**Pull request by tejank10**
`flipkernel` support for `conv` and related tests

### CODE REVIEW

**Comment by maleadt** [comment]
Test failures seem related?

**Comment by maleadt** [comment]
Then you should add version bounds, and you can add `NNLib` to the list of packages that need to be checked-out from master in `runtests.jl`.

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
Removed comment by bors was a try time-out (see https://forum.bors.tech/t/usage-with-gitlab-ci/245).

**Comment by maleadt** [comment]
Please don't merge branches like that, especially not your own...

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
Great, thanks!

**Comment by tejank10** [comment]
Thanks for the changes Tim, I'll take care of the rebase in the future.

**Pull request merged**
