### PR TITLE
#362: specialise reduce, minimum and maximum for CuArrays

### PR DESCRIPTION
**Pull request by tanhevg**
Fix for #362

### CODE REVIEW

**Comment by tanhevg** [comment]
Some tests are failing on master on my machine. These are still broken in this PR.
[redacted_tests_output.txt](https://github.com/JuliaGPU/CuArrays.jl/files/3549964/tests_output.txt)

**Comment by maleadt** [comment]
Solver issues are unrelated. Thanks!

**Comment by tanhevg** [comment]
> bors try

Is that how CI is triggered? Can I do this myself, if required for future PRs?

**Comment by maleadt** [comment]
> Is that how CI is triggered? Can I do this myself, if required for future PRs?

I wish, but I haven't figured out a way to configure it that way. It's only available to JuliaGPU members, and once Gitlab supports so we won't need bors at all (https://gitlab.com/gitlab-org/gitlab-ee/issues/5667).

**Pull request merged**
