### PR TITLE
CUBLAS: wrap gemmStridedBatched

### LINKED ISSUE #95: CUBLAS: batched GEMM wrapper
https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemmstridedbatched

### PR DESCRIPTION
**Pull request by Roger-luo**
This should fix #95

### CODE REVIEW

**Comment by maleadt** [comment]
bors try

**Comment by Roger-luo** [comment]
can you try again, I wrote a typo.

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
Hmm, bors doesn't work completely yet. Will retry once the timeout hits.

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
Squashed and rebased.
bors try

**Comment by maleadt** [comment]
Looks good, thanks!

**Pull request merged**
