### PR TITLE
Auto-generated library wrappers

### PR DESCRIPTION
**Pull request by maleadt**
Depends on https://github.com/JuliaGPU/CUDAapi.jl/pull/88

### CODE REVIEW

**Comment by maleadt** [comment]
@kshyatt you might be interested in this -- no more manually creating ccall wrappers :tada:

CUBLAS headers depend on https://github.com/JuliaGPU/CUDAapi.jl/pull/88

**Comment by kshyatt** [comment]
🎉 

but also, love too be made irrelevant by the relentless march of technology

**Comment by maleadt** [comment]
Man, these CUSPARSE/CUSOLVER headers are _massive_! How did you ever do this manually, @kshyatt?! Some of them are also badly documented, or at least with respect to the memory type (host, device, or both), so there will probably be some issues with the newly generated wrappers.

**Comment by kshyatt** [comment]
The ability of grad students to procrastinate is one of the most powerful forces between Heaven and Earth.

**Comment by maleadt** [comment]
Looks like two failures that happen occasionally trigger much more often here:

```
gebrd!: Test Failed at /builds/JuliaGPU/CuArrays.jl/test/solver.jl:172
  Expression: e ≈ h_E
   Evaluated: Float32[7.435446,  -1.2994764, -1.0428679, 0.9250362, 0.8790622,  1.0119101, -0.6535586,  -0.6603617, 0.49858388, NaN]
            ≈ Float32[7.4354453, -1.2994765, -1.0428677, 0.925036,  0.87906194, 1.0119098, -0.65355843, -0.6603623, 0.49858359, 0.0]
```

A wild NaN appeared!

```
(eltyA, eltyC) = (Float16, Float16): Test Failed at /builds/JuliaGPU/CuArrays.jl/test/tensor.jl:495
  Expression: reshape(C, (dimsC..., ones(Int, NA - NC)...)) ≈ prod(permutedims(A, p); dims=(NC + 1:NA...,))
   Evaluated: Float16[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; … ; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0] ≈ Float16[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0; … ; 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0]
```

Not sure what's up here, the output is incomplete.
@kshyatt, any thoughts?

**Comment by kshyatt** [comment]
At least in that `gebrd!` case it's actually LAPACK that's showing the `NaN` ... a bit odd...

**Pull request merged**
