### PR TITLE
Fix bug in mul!

### PR DESCRIPTION
**Pull request by andreasnoack**
~~Increase mul! coverage in tests~~

Restructure BLAS tests a bit to make it easier to locate test failures

### CODE REVIEW

**Comment by maleadt** [comment]
Fold into https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/testsuite/blas.jl? Not sure which part of the API is unique to CuArrays.BLAS though.

**Comment by andreasnoack** [comment]
It looks like a natural home for these tests. I'll move that part over but leave the bugfix and reformatting in this PR.

**Comment by andreasnoack** [comment]
I've opened https://github.com/JuliaGPU/GPUArrays.jl/pull/143 which should cover the same as here. I'll update this PR once we have a new release of GPUArrays.

**Comment by andreasnoack** [comment]
The tests revealed that a few methods were missing. This still depends on https://github.com/JuliaGPU/GPUArrays.jl/pull/144 and https://github.com/JuliaGPU/CuArrays.jl/pull/118 accurate so we should restart the tests once they are merged and we have a new release of GPUArrays.

**Pull request merged**
