### PR TITLE
get high level sparse wrappers working

### PR DESCRIPTION
**Pull request by kshyatt**
lotsa type funny business going on here, but these wrappers now seem to be working for me!

### CODE REVIEW

**Comment by kshyatt** [comment]
bors try

**Comment by kshyatt** [comment]
Not quite sure why, but the old `istriu`/`istril` code wasn't getting picked up at all...

**Comment by kshyatt** [comment]
Is this NNLib at it again?

**Comment by KristofferC** [comment]
https://github.com/FluxML/NNlib.jl/pull/94

**Pull request merged**
