### PR TITLE
Wrap and test CUBLAS.gemmEx

### PR DESCRIPTION
**Pull request by kshyatt**
Lets us use Tensor Cores on Volta GPUs. Should at some point update to let `computeType` assume all its possible values but for now this works.

### CODE REVIEW

**Comment by maleadt** [comment]
> Lets us use Tensor Cores on Volta GPUs.

Shouldn't that happen automatically by us setting the math mode on recent GPUs and on fast math mode?

> To make use of the Tensor Core units introduced with Volta GPUs, these Tensor Core units must first be enabled by configuring cublas MathMode (see cublasSetMathMode()), or by explicitly selecting the tensor op algorithm in cublasGemmEx() (see cublasGemmAlgo_t). 

https://github.com/JuliaGPU/CuArrays.jl/blob/c3259aedd4d9aa2a9b6492e4dbb8c636afba0de1/src/blas/CUBLAS.jl#L45-L49

Nonetheless, good to have the additional wrappers though.

**Comment by kshyatt** [comment]
You're right about the tensor cores.

**Comment by kshyatt** [comment]
Looks like the test failures are due to 
```
gemmEx!: Error During Test at /builds/JuliaGPU/CuArrays.jl/test/blas.jl:446
  Got exception outside of a @test
  CUBLASError: an absent device architectural feature is required (code 8, CUBLAS_STATUS_ARCH_MISMATCH)
```
So we need some sort of condition to make sure this function is only callable on appropriate GPUs?

**Comment by maleadt** [comment]
> So we need some sort of condition to make sure this function is only callable on appropriate GPUs?

If that's the cause, then yes. We always run at least on test on a high compute capability, so that would ensure coverage.

**Comment by maleadt** [comment]
Segfault during finalizers:

```
 cublasDestroy_v2 at /builds/JuliaGPU/CuArrays.jl/.julia/artifacts/f583fb4bf816d52e5ac27a2035f4d25768b0814c/lib/libcublas.so (unknown line)
cublasXtDestroy at /builds/JuliaGPU/CuArrays.jl/.julia/artifacts/f583fb4bf816d52e5ac27a2035f4d25768b0814c/lib/libcublas.so (unknown line)
macro expansion at /builds/JuliaGPU/CuArrays.jl/src/blas/libcublas.jl:2367 [inlined]
macro expansion at /builds/JuliaGPU/CuArrays.jl/src/memory.jl:250 [inlined]
macro expansion at /builds/JuliaGPU/CuArrays.jl/src/blas/error.jl:56 [inlined]
cublasXtDestroy at /builds/JuliaGPU/CuArrays.jl/.julia/packages/CUDAapi/XuSHC/src/call.jl:93
#680 at /builds/JuliaGPU/CuArrays.jl/src/blas/CUBLAS.jl:66 [inlined]
context! at /builds/JuliaGPU/CuArrays.jl/.julia/packages/CUDAnative/jBXfB/src/init.jl:147
#679 at /builds/JuliaGPU/CuArrays.jl/src/blas/CUBLAS.jl:65
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2141 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1631 [inlined]
run_finalizer at /buildworker/worker/package_linux64/build/src/gc.c:231
jl_gc_run_finalizers_in_list at /buildworker/worker/package_linux64/build/src/gc.c:317
jl_gc_run_all_finalizers at /buildworker/worker/package_linux64/build/src/gc.c:345
jl_atexit_hook at /buildworker/worker/package_linux64/build/src/init.c:257
jl_exit at /buildworker/worker/package_linux64/build/src/jl_uv.c:629
exit at ./initdefs.jl:28 [inlined]
_start at ./client.jl:463
jfptr__start_2084.clone_1 at /usr/local/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2135 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1631 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:96
main at /buildworker/worker/package_linux64/build/ui/repl.c:217
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /usr/local/bin/julia (unknown line)
```

Ref https://github.com/JuliaGPU/CuArrays.jl/issues/662

**Comment by kshyatt** [comment]
Incorporated over at CUDA.jl

**Pull request closed without merging**
