### PR TITLE
Updates for CUTENSOR 1.0

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@kshyatt Bumped the test bounds to the correct values, can you run the tests now?

The tests now seem to trigger a bunch of CUTENSOR_UNSUPPORTED errors.

**Comment by kshyatt** [comment]
bors try

**Comment by kshyatt** [comment]
Hmmm all of a sudden we're not testing CUTENSOR!

**Comment by maleadt** [comment]
> Hmmm all of a sudden we're not testing CUTENSOR!

we are, check the 1.2 builder. not all CI systems have a recent enough GPU, so it only forces to run them on one of them (1.2 since that's the current stable version)

**Comment by kshyatt** [comment]
Ah cool, I looked at the wrong builder - thanks!

**Comment by maleadt** [comment]
:tada:

**Comment by Jutho** [comment]
Do I see correctly that the contraction tests are only ran for real `eltype`?

**Comment by maleadt** [comment]
I ran into a bunch of "operation unsupported" errors, after which @kshyatt had a call with Paul and removed a bunch of tests, so I'm assuming that was the intention...

**Pull request merged**
