### PR TITLE
Some improvements to test coverage

### PR DESCRIPTION
**Pull request by andreasnoack**
Enable blas, fft, and solver tests and fix a few minor issues with the solver tests

### CODE REVIEW

**Comment by andreasnoack** [comment]
@maleadt It looks like the cudnn tests trigger an assertion error in LLVM

**Comment by maleadt** [comment]
Yes, this has been a recurring problem: https://github.com/JuliaGPU/CuArrays.jl/pull/50#issuecomment-363354166
I wouldn't have merged that PR, because it essentially breaks CI...

**Comment by maleadt** [comment]
Alternatively, you can guard the failing test behind a [`ENV["CONTINUOUS_INTEGRATION"]`](https://github.com/maleadt/juliagpu-buildbot/blob/397ad8b3bcbbd6e2dade1115201af753392f8e78/master.cfg#L321-L323) check

**Comment by andreasnoack** [comment]
I think I got it now. The CUDNN tests just have to be run before any of blas, solver, and fft.

**Pull request merged**
