### PR TITLE
Actually test error throwing for lsvqr

### PR DESCRIPTION
**Pull request by kshyatt**
Can't test mismatched dimensions if the GPU doesn't know about them

### CODE REVIEW

**Comment by maleadt** [comment]
`CUBLAS_STATUS_ALLOC_FAILED` -- these calls allocate? the calls should be wrapped in an `@allocates` like some CURAND calls are.

**Comment by kshyatt** [comment]
Oh, yeah, because they are making copies. Sorry about that.

**Comment by maleadt** [comment]
Basically this but with a different code: https://github.com/JuliaGPU/CuArrays.jl/blob/0cdf32ce11263446c17297f62157e5f944912e21/src/rand/wrappers.jl#L13-L19

**Comment by maleadt** [comment]
Also, if you know how much memory the call would probably allocate, pass that as the `nb` kwarg. Otherwise we might end up deallocating all cached memory.

**Pull request merged**
