### PR TITLE
Fix build with CUDAapi 0.3.0

### PR DESCRIPTION
**Pull request by iblis17**
and bump CUDAapi requirement

### CODE REVIEW

**Comment by iblis17** [comment]
well, I want set of version number of `CUDA*`/`Cu*` which works together.
(just doing some works with Flux, but frustrated with the compatibility problem

**Comment by iblis17** [comment]
I'm on Julia `0.6.3-pre.1`, with CUDA 9.1.
I tried lots of combination, still cannot get `CuArray` work, I give up now.
Also notice a breaking change: from CUDAdrv 0.5.2 -> 0.5.3. It causes CUDAapi 0.2.1 build fail, due to the `debug` macro got deleted.

seems CUDA 9 + Julia 0.6 is infeasible.

**Comment by MikeInnes** [comment]
Yeah, I think we need to wait for 0.7 to fully support all of the new stuff.

**Comment by maleadt** [comment]
Sorry, I've been changing quite some stuff. Hadn't seen your PR, the fix is already included in #40.

**Comment by maleadt** [comment]
> seems CUDA 9 + Julia 0.6 is infeasible.

Missed this bit. Yes, sadly this combination is impossible. CUDA 9 contains breaking changes we cannot generate code for with Julia 0.6; Julia 0.7 contains a patch making it possible again.

**Pull request closed without merging**
