### PR TITLE
Simplify package matching.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Just a thought, but perhaps we should just check in a manifest for this purpose? CI can then always use a known-good set of packages/git revisions as chosen by PR authors, and we can reset to releases just before tagging.

**Comment by maleadt** [comment]
But then CI wouldn't detect issues caused by package upgrades. I also don't know how to efficiently generate a Manifest for eg. CuArrays; I'm developing those packages in a shared environment so my manifest contains many more packages, and I `dev` most packages so there's no tree hash.

**Comment by vchuravy** [comment]
I liked having the ability to jointly push branches and test development that way.

**Comment by maleadt** [comment]
> I liked having the ability to jointly push branches and test development that way.

As do I, but with the proposed Bors workflow the branch is always `trying` or `staging`...

**Comment by vchuravy** [comment]
Ah ok. This makes sense then. So we are going full bors?

**Comment by maleadt** [comment]
> So we are going full bors?

It sees like the only way to support CI for non-JuliaGPU members, which arguably is a more important feature than experimental branch matching.

**Comment by maleadt** [comment]
I'm suspecting a library version error, so adding some code to report that.

**Comment by maleadt** [comment]
bors try

**Comment by maleadt** [comment]
Interesting. Had forgotten to run `ldconfig` after updating CUDA so it had picked up an incompatible mix of libraries.

**Comment by maleadt** [comment]
Seems like I need to restart the process.
bors r+

**Comment by maleadt** [comment]
Doc failure is CUDAapi not being tagged. Merging!

**Pull request merged**
