### PR TITLE
Adapt to the new CUDAdrv.CuPtr pointer type

### PR DESCRIPTION
**Pull request by maleadt**
See https://github.com/JuliaGPU/CUDAdrv.jl/pull/125

I'd appreciate some help on this; it's a pretty mechanical change: run the test-suite, spot conversion errors, have a look at the underlying `ccall` and change `Ptr` arguments to `CuDevicePtr` arguments when if they pass an `CuArray`.

### CODE REVIEW

**Comment by maleadt** [comment]
OK, this wasn't fun. All but one test pass now.

**Comment by maleadt** [comment]
I think this is starting to look good. Unless there's objections, I'll go ahead and merge this later today.

@MikeInnes this of course needs fixing of the cudnn/curnn wrappers in Flux.
Maybe now is a good time to move them into CuArrays.

Also, this generally has been a pretty fragile change where I had to peer the wrappers next to the NVIDIA docs and inspect every `Ptr` in every `ccall`. Needless to say, this is pretty error-prone. Testing has flushed out many errors, but our coverage is bad so expect fallout from this change.

**Comment by MikeInnes** [comment]
Ok, I'll look at copying the Flux wrappers over soon.

**Comment by maleadt** [comment]
bors try

**Pull request merged**
