### PR TITLE
Adding missing `cudnnSetConvolutionGroupCount` to pointers.json

### PR DESCRIPTION
**Pull request by arhik**
This change is necessary for setting `groupcount` incase of depthwise and groupwise convolutions.

The original cudnn api is as follows:

`cudnnStatus_t cudnnSetConvolutionGroupCount(  `
`  cudnnConvolutionDescriptor_t    convDesc,  ` 
` int                             groupCount)`

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! You'll need to change the wrappers themselves too, though. The `pointers.json` is a database used if you manually run `wrap.jl`, but we don't do that automatically and commit the resulting `libcudnn.jl`.

**Comment by maleadt** [comment]
We have the API already: https://github.com/JuliaGPU/CuArrays.jl/blob/b64c6c0866ef978552d684c022132474ce2f7693/src/dnn/libcudnn.jl#L388-L392

**Comment by arhik** [comment]
Sorry. Function pointer was returning null so I assumed its missing. I didn't realized its declared at other place. Thanks. 

> Why do you need this entry? We only need it to resolve pointer arguments, which this call doesn't have.

I was just following other definitions. I was curious to know the purpose of `null` declarations as a followup. You have shed some light on it. Interesting!

**Comment by maleadt** [comment]
Yeah, this stuff isn't documented at all, purely internal for generating wrappers. `null` indicates this argument isn't special, and can be used as-is. In other cases, when dealing with pointers, the argument indicates what kind of pointer we're dealing with (a pointer to CPU memory, to GPU memory, or to potentially both).

**Pull request closed without merging**
